<a href="https://colab.research.google.com/github/HernandezFer/Monitorias/blob/main/Monitoria1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python

Es un lenguaje de programación orientado a objetos, el cual fue lanzado en 1991 por Van Rossum. Es uno de los lenguajes de programación más populares del mundo.


#operadores aritmeticos

Reglas de orden de operadores

1. Primero se evaluan las expresiones con parentesis. si hay parenetsis anidados, se resuelven de adentro hacia afuera
2. operaciones exponenciales
3. multiplicacion
4. sumas y restas


In [ ]:
2+2 #suma

4

In [ ]:
3-1 #resta

2

In [ ]:

2*2 #multiplicación

4

In [ ]:
5/2 #división

2.5

In [ ]:
2**2 #potencia 

4

In [ ]:
10%2 #residuo ,módulo Par-Impar

0

In [ ]:
10//3 #división entre enteros, lo redonde al menor valor

3



Operadores en comparacion

In [ ]:
5>4 

True

In [ ]:
4>5 #mayor que

False

In [ ]:
4<=5 #menor o igual

True

In [ ]:
4>=5 #mayor o igual


False

In [ ]:
4==5 #igual a

False

In [ ]:
10/2

5.0

In [ ]:

4!=5 #diferente de

True

Operadores logicos -Booleanos

and or not
and (y): todas deben ser verdaderas para que la afirmación sea verdadera

or (o): al menos una debe ser verdadera para que la afirmación sea verdadera

not (no): niega el valor de verdad

In [ ]:
4<5 and 5>6

False

In [ ]:
4<5 and 5<6

True

In [ ]:
4<5 or 5>6

True

In [ ]:
4>5 or 5>6

False

In [ ]:
not 4<5

False

Tipos de datos 

ingresos: numero; float

edad: numero; int

estrato: numero; int

trabajo: binario; bool

nivel_formacion: texto; str

años_escolaridad: numero; int

regimen_salud: texto; str

In [ ]:
type(4) # entero

int

In [ ]:
type(4.5) #float o decimal

float

In [ ]:
type("carro") #string o cadena de texto

str

In [ ]:
a = 4
b = 3
c = 2
d = 10
e = 'carro'
f = 'elefante'
g = True
h = False

In [ ]:
f

'elefante'

In [ ]:
b*c

6

In [ ]:
type(False) #booleano

bool

Variables 

Variables en minúscula

Separación con un guión bajo

No empezar con un número


In [ ]:
a = 4
b = 3
c = 2
d = 10
e = 'carro'
f = 'elefante'
g = True
h = False

In [ ]:
3*True

3

In [ ]:
x = 4

In [ ]:
y = True

In [ ]:
b = 3

In [ ]:
c = 2

In [ ]:
d = 10

In [ ]:
h = False

In [ ]:
y-x

-3

In [ ]:
z = 4.5

In [ ]:
m = 'carro'

In [ ]:
x, y, z, m

(4, True, 4.5, 'carro')

In [ ]:
n = 'elefante'

In [ ]:
n+m

'elefantecarro'

Estructuras de datos

Listas []


In [ ]:
lista_vacia = []

In [ ]:
type(lista_vacia)

list

In [ ]:
lista = [1,3,6,7,8,12,4,7,2,4,98]

In [ ]:
lista.append(7) #agregar a la última posición de la lista

In [ ]:
lista

[1, 3, 6, 7, 8, 12, 4, 7, 2, 4, 98, 7]

In [ ]:
lista.count(7) #cuenta cuántas veces se repite el elemento en la lista

3

In [ ]:
lista.extend([3,4,5,6,7,8]) #agregar más de un elemento

In [ ]:
lista

[1, 3, 6, 7, 8, 12, 4, 7, 2, 4, 98, 7, 3, 4, 5, 6, 7, 8]

In [ ]:
lista.index(4) #preguntamos por la posición del elemento

6

In [ ]:
lista[4]

8

In [ ]:
lista.insert(0, 10) #insertamos por posición al elemento (posición, elemento)

In [ ]:
lista

[10, 1, 3, 6, 7, 8, 12, 4, 7, 2, 4, 98, 7, 3, 4, 5, 6, 7, 8]

In [ ]:
lista.remove(4) #elimina el elemento

In [ ]:
lista

[10, 1, 3, 6, 7, 8, 12, 7, 2, 4, 98, 7, 3, 4, 5, 6, 7, 8]

In [ ]:
lista.pop() #elimina el último elemento

8

In [ ]:
lista.pop(4) #elimina elemento por posición

7

In [ ]:
lista.sort() #organizar de menor a mayor

In [ ]:
lista

[1, 2, 3, 3, 4, 4, 5, 6, 6, 7, 7, 7, 8, 10, 12, 98]

In [ ]:
lista.sort(reverse=True) #organizar de mayor a menor

In [ ]:
lista

[98, 12, 10, 8, 7, 7, 7, 6, 6, 5, 4, 4, 3, 3, 2, 1]

In [ ]:
lista.clear()

In [ ]:
lista

[]

Tupla ( )

In [ ]:
tupla = (3,4,6,7,21,9,9,9,5,3,6)

In [ ]:
tupla.count(9) #cuenta cuántas veces se repite el elemento en la tupla

3

In [ ]:
tupla.index(4)

1

In [ ]:
tupla[10]

6

In [ ]:
type(tupla)

tuple

Diccionarios 

{'key':'values'} 

In [ ]:
dict_1 = {'key1':'values_1','key2':'values_2','key3':'values_3'}

In [ ]:
dict_1['key3']

'values_3'

In [ ]:
dict_2 = {'Idiomas':['es','en','it','po','fr','de','sw'],
          'Países':['España','USA','Italia','Brasil','Francia','Alemania','Kenia'],
          'Capitales':['Madrid','Washington','Roma','Brasilia','Paris','Berlín','Nairobi']}

In [ ]:
dict_2['Idiomas'].append('ru')

In [ ]:
dict_2['Países'].append('Rusia')

In [ ]:
dict_2['Capitales'].append('Moscú')

In [ ]:
dict_2.items()

dict_items([('Idiomas', ['es', 'en', 'it', 'po', 'fr', 'de', 'sw', 'ru']), ('Países', ['España', 'USA', 'Italia', 'Brasil', 'Francia', 'Alemania', 'Kenia', 'Rusia']), ('Capitales', ['Madrid', 'Washington', 'Roma', 'Brasilia', 'Paris', 'Berlín', 'Nairobi', 'Moscú'])])

In [ ]:
dict_2.keys()

dict_keys(['Idiomas', 'Países', 'Capitales'])

In [ ]:
dict_2.values()

dict_values([['es', 'en', 'it', 'po', 'fr', 'de', 'sw', 'ru'], ['España', 'USA', 'Italia', 'Brasil', 'Francia', 'Alemania', 'Kenia', 'Rusia'], ['Madrid', 'Washington', 'Roma', 'Brasilia', 'Paris', 'Berlín', 'Nairobi', 'Moscú']])

In [ ]:
dict_2.clear()

In [ ]:
import pandas as pd
df = pd.DataFrame(dict_2)

Funciones

In [ ]:
print('Hola, mundo') #imprimir el elemento

Hola, mundo


In [ ]:
print(4)

4


In [ ]:
print(x)

4


In [ ]:
input()

hola


'hola'

In [ ]:
nombre = input()
apellido = input()
edad = input()

María
Hernández
24


In [ ]:
edad

'24'

In [ ]:
int(edad) #transforma en un entero

24

In [ ]:
float(edad) #transforma en un float

24.0

In [ ]:
str(3241243465) #transforma en un string

'3241243465'

In [ ]:
list(range(0,10,2)) #punto de partida, punto de llegada, stepsize

[0, 2, 4, 6, 8]

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
lista_valores = list(range(20))

In [ ]:
lista_valores

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
max(lista_valores) #número mayor

19

In [ ]:
min(lista_valores) #número menor

0

In [ ]:
sum(lista_valores) #sumatoria

190

In [ ]:
abs(-3) #valor absoluto

3

In [ ]:
n = 12341.234625865

In [ ]:
round(n, 3) #función para redondear (número a redondear, número de dígitos)

12341.235

In [ ]:
len(lista_valores) #cuántos elementos tiene la lista

20

Funcion

def #nombre_funcion(#argumentos):
  #cuerpo de la función

In [ ]:
# Estructura
def nombre(argumentos):
  acciones
  return resultado

In [ ]:
def suma(a,b):
  return a+b

In [ ]:
suma(3,4)

7

In [ ]:
def descriptivo(a):
  media = sum(a)/len(a)
  return sum(a), len(a), media

In [ ]:
descriptivo(lista_valores)

(190, 20, 9.5)

In [ ]:
def f(x):
   return x**2+3*x

In [ ]:
f(6)

54

In [ ]:

def f(x,y,z):
  return x**2+z+3*y**2

Condicionales 

if 

elif 

else

In [ ]:
a = 10
b = 4

if a>b:
  print(f'{a} es mayor que {b}')
elif a<b:
  print(f'{a} es menor que {b}')
else:
  print(f'{a} es igual a {b}')


10 es mayor que 4


In [ ]:
def tipo(a):
  if type(a)==int:
    return 'entero'
  elif type(a)==str:
    return 'texto'
  elif type(a)==float:
    return 'decimal'
  else:
    return 'tipo diferente de dato'

def par_impar(a):
  if type(a)==int:
    if a%2==0:
      print(f'{a} es par')
      if a<10:
        print(f'{a} es menor a 10.')
      elif a>=10 and a<25:
        print(f'{a} es mayor o igual a 10.')
      else:
        print(f'{a} es mayor a 25.')
    else:
      print(f'{a} es impar')
  else:
    print(f'{a} no es un entero es un {tipo(a)}. La función solo trabaja con enteros.')

In [ ]:
tipo(3)

'entero'

In [ ]:
par_impar(26)

26 es par
26 es mayor a 25.


In [ ]:
par_impar(8.8)

8.8 no es un entero es un decimal. La función solo trabaja con enteros.


In [ ]:
tipo(7.9)

'decimal'

In [ ]:
salario=int(input("salario:"))
salario_minimo=1000000

if salario>salario_minimo:
  gasto=int(input("Gastos:"))
  print("Usted gana mas del salario minimo y sus ahorros son de {}".format(salario-gasto))
elif salario==salario_minimo:
  gasto=int(input("Gastos:"))
  print(f"Usted gana excatamente el salario minimo y sus ahorros son de {salario-gasto}")
else:
  gasto=int(input("Gastos:"))
  print(f"Ustede gana menos del salario minimo y sus ahorros son de {salario-gasto}")

Bucle

For
for i in iterable:
  #cuerpo del bucle

In [ ]:
lista = list(range(10))

In [ ]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for numero in lista:
  print(numero)

0
1
2
3
4
5
6
7
8
9


In [ ]:
lista_materias = ['mate1','mate2','mate3','micro1','micro2','micro3','macro1','macro2','macro3']
lista_vistas = ['mate1','mate2','micro1','micro2','macro1']

In [ ]:
for materia in lista_materias:
  if materia in lista_vistas:
    print(f'Ya vi {materia}')
  else:
    print(f'No he visto {materia}')

Ya vi mate1
Ya vi mate2
No he visto mate3
Ya vi micro1
Ya vi micro2
No he visto micro3
Ya vi macro1
No he visto macro2
No he visto macro3


In [ ]:
for numero in lista:
  par_impar(numero)

0 es par
0 es menor a 10.
1 es impar
2 es par
2 es menor a 10.
3 es impar
4 es par
4 es menor a 10.
5 es impar
6 es par
6 es menor a 10.
7 es impar
8 es par
8 es menor a 10.
9 es impar


In [ ]:
semestre_materias = {'primero':['mate1','fundamentos','historia'],
                     'segundo':['mate2','micro1','historia del pensamiento'],
                     'tercero':['mate3','micro2','macro1'],
                     'cuarto':['economate','marcro2','tecnicas']}

In [ ]:
for semestre in semestre_materias.keys():
  for materia in semestre_materias[semestre]:
    print(semestre,materia)

primero mate1
primero fundamentos
primero historia
segundo mate2
segundo micro1
segundo historia del pensamiento
tercero mate3
tercero micro2
tercero macro1
cuarto economate
cuarto marcro2
cuarto tecnicas


In [ ]:
for i in range(3):
  for j in range(3):
    print(i,j)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [ ]:
semestre_materias['segundo']

['mate2', 'micro1', 'historia del pensamiento']

In [ ]:
semestre_materias.values()

dict_values([['mate1', 'fundamentos', 'historia'], ['mate2', 'micro1', 'historia del pensamiento'], ['mate3', 'micro2', 'macro1'], ['economate', 'marcro2', 'tecnicas']])

In [ ]:
for numero in range(20):
  if numero%2==0:
    continue
  elif numero==17:
    break
  else:
    print(f'{numero} si va')

1 si va
3 si va
5 si va
7 si va
9 si va
11 si va
13 si va
15 si va


In [ ]:
lista = [1,2,3,4]
lista_2 = [5,6,7,8]

for i,j in zip(lista,lista_2):
  print(i,j)

1 5
2 6
3 7
4 8


In [ ]:

for i in enumerate(lista_2):
  print(i)
  

(0, 5)
(1, 6)
(2, 7)
(3, 8)


MONITORIA 2


---



---



While

while #condición:
  #cuerpo del bucle
  

In [ ]:
velocidad=10
while velocidad>0:
  velocidad-=5
  print(f"La Velocidad es de {velocidad} km/h")
  if velocidad==0:
    print("se detuvo el motor")

La Velocidad es de 5 km/h
La Velocidad es de 0 km/h
se detuvo el motor


Vamos a crear listas por medio de bucles

In [ ]:
lista_pares=[i for i in range(0,25) if i%2==0]   #[elemento_nuevo for elemento in iterable_elementos if sentencia]
lista_pares

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]

Sympy

Sistema de álgebra computacional

In [1]:
from sympy import * 
Import sympy as sy

x=Symbol('x')
x,y,z= symbols(['x','y','z'])

In [2]:
pi**2

pi**2

In [3]:
pi.evalf()

3.14159265358979

In [12]:
sqrt(64)

8

In [5]:
oo


oo

In [ ]:
Calcular la raiz de 2 con 10 decimales

In [75]:
sqrt(2).evalf(90)

1.41421356237309504880168872420969807856967187537694807317667973799073247846210703885038753

In [ ]:
x**2

x**2

In [ ]:
x+x

2*x

In [15]:

f = x**2 + 5*x +6

In [16]:
f

x**2 + 5*x + 6

In [17]:
solve(f)

[-3, -2]

In [18]:
factor(f)

(x + 2)*(x + 3)

In [19]:
degree(f)  #el grado de la funcion 

2

In [20]:
g = x**3 + 2*x**2 + 10

In [21]:
g

x**3 + 2*x**2 + 10

In [22]:
f+g

x**3 + 3*x**2 + 5*x + 16

# para un solo simbolo se usa Symbol y para varios symbols

In [23]:

integrate(f,x)

x**3/3 + 5*x**2/2 + 6*x

In [77]:
x,y,z=symbols(["x","y","z"])

In [25]:
f=x**2+3*x+4*x*y

In [26]:
f

x**2 + 4*x*y + 3*x

In [27]:
integrate(f,y)

2*x*y**2 + y*(x**2 + 3*x)

In [79]:

diff(x*3**y*x,x)

2*3**y*x

In [29]:
expand((x+y)**3)

x**3 + 3*x**2*y + 3*x*y**2 + y**3

In [30]:
simplify((x+x*y)/x) #simplificación de exponentes

y + 1

In [31]:
trigsimp( sin(x) / cos(x))

tan(x)

In [36]:
logcombine(ln(x)-ln(1-x))

log(x) - log(1 - x)

In [38]:
#Limites

#limit(función, variable, punto)
#calcular el límite de f(x) como x -> 0, deberías usar la siguiente expresión limit(f, x, 0)

In [39]:
limit(sin(x)/x, x, 0)

1

In [40]:
limit(x, x, oo)

oo

In [41]:
diff(sin(x), x)

cos(x)

In [42]:
integrate(sin(x), x)

-cos(x)

In [43]:
integrate(log(x), x)

x*log(x) - x

In [44]:
Matrix([[1,0], [0,1]])

Matrix([
[1, 0],
[0, 1]])

In [54]:
x = Symbol('x')
y = Symbol('y')
A = Matrix([[1,x], [y,1]])
A

Matrix([
[1, x],
[y, 1]])

In [66]:
x = Symbol('x')
M = eye(3) * x
M

Matrix([
[x, 0, 0],
[0, x, 0],
[0, 0, x]])

In [80]:
 M.subs(x, 9)

Matrix([
[9, 0, 0],
[0, 9, 0],
[0, 0, 9]])

In [81]:
n= Matrix(( [1, 2, 3], [3, 6, 2], [2, 0, 1] ))

In [82]:
n

Matrix([
[1, 2, 3],
[3, 6, 2],
[2, 0, 1]])

In [69]:
n.det()

-28

In [70]:
M.inv()

Matrix([
[1/x,   0,   0],
[  0, 1/x,   0],
[  0,   0, 1/x]])

In [72]:
n[1,2]=x
n[2,1] = 2*x
n[1,1] = sqrt(x)
n

Matrix([
[1,       2, 3],
[3, sqrt(x), x],
[2,     2*x, 1]])

In [59]:
1/( (x+2)*(x+1) )

1/((x + 1)*(x + 2))

In [61]:
apart(1/( (x+2)*(x+1) ), x)

-1/(x + 2) + 1/(x + 1)

In [62]:
diff(sin(2*x), x, 1) #derivada de 1er orden

2*cos(2*x)

In [63]:
diff(sin(2*x), x, 2)

-4*sin(2*x)

In [64]:
diff(sin(2*x), x, 3) 

-8*cos(2*x)


Atrapar errores

try:

except:

In [ ]:
def dividir(a,b):
  try:
    print(a/b)
  except ZeroDivisionError:
    print('Error')
    print('-------')
    print('El segundo elemento no puede ser cero.')
  except TypeError:
    print('Error')
    print('-------')
    print('Ambos elementos deben ser números.')
  print('División realizada')

In [ ]:
dividir(4,2)

2.0
División realizada


In [ ]:
dividir(2,0)

Error
-------
El segundo elemento no puede ser cero.
División realizada


In [ ]:
dividir(120,60)

2.0
División realizada


In [ ]:
dividir('u',0)

Error
-------
Ambos elementos deben ser números.
División realizada


In [ ]:
import math as mt

In [ ]:
mt.sqrt(64)

8.0

In [ ]:
import statistics as st

In [ ]:
lista = [1,23,4,5,6,7,6,5,4,34,5,6,7,8,34,23,21,45]

In [ ]:
st.mean(lista)

13.555555555555555

In [ ]:
st.stdev(lista)

13.075447229882345

In [ ]:
st.variance(lista)

170.9673202614379

**MONITORIA 3**

---



---



NUMPY

Numpy es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos. Incorpora una nueva clase de objetos llamados arrays.

Arrays  es una estructura de datos de un mismo tipo organizada en forma de tabla o cuadrícula de distintas dimensiones.

Numpy es una librería para realizar cálculo numérico en python. La usaremos principalmente porque nos permite crear y modificar matrices, y hacer operaciones sobre ellas con facilidad.

Para comenzar a usar numpy, debemos importar la librería. En este caso la vamos a importar, y darle un sobrenombre al mismo tiempo, np, para que el código sea más legible

np.array(lista) : Crea un array a partir de la lista o tupla lista y
devuelve una referencia a él. El número de dimensiones del array dependerá de las listas o tuplas anidadas en lista:

In [84]:
# importamos la librería numpy, y le damos como nombre np dentro del programa
import numpy as np


In [85]:
lista=[25,12,15,66,12.5]
vector=np.array(lista)
print(vector)

[25.  12.  15.  66.  12.5]


¿Cuál es la diferencia entre vector y lista? Que vector, al ser un arreglo de numpy, nos permite hacer varias operaciones matemáticas de forma muy simple.

In [86]:
print("- vector original")
print(vector)

print("- sumarle 1 a cada elemento del vector:")
print(vector+1)
print("- multiplicar por 5 cada elemento del vector:")
print(vector*5)

print("- suma de los elementos:")
print(np.sum(vector))

print("- promedio (media) de los elementos:")
print(np.mean(vector)) # 

print("- el vector sumado a si mismo:")
print(vector+vector)
print("- suma de vectores vector1 y vector2 (mismo tamaño):")
vector2=np.array([11,55,1.2,7.4,-8])
print(vector+vector2)

- vector original
[25.  12.  15.  66.  12.5]
- sumarle 1 a cada elemento del vector:
[26.  13.  16.  67.  13.5]
- multiplicar por 5 cada elemento del vector:
[125.   60.   75.  330.   62.5]
- suma de los elementos:
130.5
- promedio (media) de los elementos:
26.1
- el vector sumado a si mismo:
[ 50.  24.  30. 132.  25.]
- suma de vectores vector1 y vector2 (mismo tamaño):
[36.  67.  16.2 73.4  4.5]


In [93]:
print(vector[3])
print(vector[1:6])
print(vector[1:])
print(vector[:4])
print(vector[:])

66.0
[12.  15.  66.  12.5]
[12.  15.  66.  12.5]
[25. 12. 15. 66.]
[25.  12.  15.  66.  12.5]


In [ ]:
print("- Vector de ceros:")
vector_ceros=np.zeros(5)
print(vector_ceros)

print("- Vector de unos:")
vector_unos=np.ones(5)
print(vector_unos)


#Combinando este tipo de creaciones con las operaciones aritméticas,
#podemos hacer varias inicializaciones muy rápidamente
# Por ejemplo, para crear un vector cuyos valores iniciales son todos 2.

print("- Vector con todos los elementos con valor 2:")
vector_dos=np.zeros(5)+2
print(vector_dos)

print("- Vector con todos los elementos con valor 2 (otra forma):")
vector_dos_otro=np.ones((5))*2
print(vector_dos_otro)

- Vector de ceros:
[0. 0. 0. 0. 0.]
- Vector de unos:
[1. 1. 1. 1. 1.]
- Vector con todos los elementos con valor 2:
[2. 2. 2. 2. 2.]
- Vector con todos los elementos con valor 2 (otra forma):
[2. 2. 2. 2. 2.]


Matrices
Los vectores son arreglos de una sola dimensión. Las matrices son arreglos de dos dimensiones; generalmente a la primera dimensión se la llama la de las filas, mientras que a la otra se la llama la de las columnas.

Por ende, para crearlas con np.array, necesitamos no una lista de valores, sino una lista de valores por cada fila, o sea, una lista de listas.

Del mismo modo, para crearlas con np.zeros o np.ones, vamos a necesitar una tupla con dos elementos, uno por cada dimensión.

In [ ]:
print("- Matriz creada con una lista de listas:")
lista_de_listas=[ [1  ,-4], 
                  [12 , 3], 
                  [7.2, 5]]
matriz = np.array(lista_de_listas)
print(matriz)


print("- Matriz creada con np.zeros:")
dimensiones=(2,3)
matriz_ceros = np.zeros(dimensiones)
print(matriz_ceros)


print("- Matriz creada con np.ones:")
dimensiones=(3,2)
matriz_unos = np.ones(dimensiones)
print(matriz_unos)

#también podemos usar np.copy para copiar una matriz 
print("- Copia de la matriz creada con np.ones:")
matriz_unos_copia=np.copy(matriz_unos)
print(matriz_unos_copia)

- Matriz creada con una lista de listas:
[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]
- Matriz creada con np.zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
- Matriz creada con np.ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
- Copia de la matriz creada con np.ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
a = np.array([1, 2, 3])

newArray = np.append (a, [10, 11, 12])

print(newArray)

[ 1  2  3 10 11 12]


In [ ]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

b = np.array([[400], [800]])

newArray = np.append(a, b, axis = 1)

print(newArray)

[[  1   2   3 400]
 [  4   5   6 800]]


In [ ]:
a = np.array([1, 2, 3])

newarray = np.insert(a, 1, 90)

print(newarray)

[ 1 90  2  3]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

newarray = np.append(a, [[50, 60, 70]], axis = 0)

print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [50 60 70]]


In [ ]:
#Eliminar un elemento
a = np.array([1, 2, 3])

newarray = np.delete(a, 1, axis = 0)

print(newarray)

[1 3]


In [ ]:
#Eliminar una fila 
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [10, 20, 30]])

newarray = np.delete(a, 1, axis = 0)

print(newarray)

[[ 1  2  3]
 [10 20 30]]


In [ ]:
# Comprobar si el arreglo NumPy está vacío
#Podemos usar el método size que devuelve el número total de elementos en el arreglo.
a = np.array([1, 2, 3])

if(a.size == 0):

    print("The given Array is empty")

else:

    print("The array = ", a)

The array =  [1 2 3]


In [ ]:
a = np.array([1, 2, 3, 4, 5])

print("5 is found at index: ", np.where(a == 5))

5 is found at index:  (array([4]),)


In [ ]:

a = np.array([1, 2, 3, 4, 5])

print("Array to list = ", a.tolist())

Array to list =  [1, 2, 3, 4, 5]


In [ ]:
# Ejemplo
# Crear una matriz de 4x9, que esté inicializada con el valor 0.5

matriz=0 #IMPLEMENTAR

print(matriz)

0


In [ ]:
lista_de_listas=[ [1  ,-4], 
                  [12 , 3], 
                  [7.2, 5]]
a = np.array(lista_de_listas)

print("Elementos individuales")
print(a[0,1])
print(a[2,1])

print("Vector de elementos de la fila 1")
print(a[1,:])

print("Vector de elementos de la columna 0")
print(a[:,0])

print("Submatriz de 2x2 con las primeras dos filas")
print(a[0:2,:])

print("Submatriz de 2x2 con las ultimas dos filas")
print(a[1:3,:])

Elementos individuales
-4.0
5.0
Vector de elementos de la fila 1
[12.  3.]
Vector de elementos de la columna 0
[ 1.  12.   7.2]
Submatriz de 2x2 con las primeras dos filas
[[ 1. -4.]
 [12.  3.]]
Submatriz de 2x2 con las ultimas dos filas
[[12.   3. ]
 [ 7.2  5. ]]


In [ ]:
lista_de_listas=[ [1,-4], 
                  [12,3], 
                  [7, 5.0]]
a = np.array(lista_de_listas)

print("- Matriz original:")
print(a)

print("- Le asignamos el valor 4 a los elementos de la columna 0:")
a[:,0]=4
print(a)


print("- Dividimos por 3 la columna 1:")
a[:,1]=a[:,1]/3.0
print(a)

print("- Multiplicamos por 5 la fila 1:")
a[1,:]=a[1,:]*5
print(a)

print("- Le sumamos 1 a toda la matriz:")
a=a+1
print(a)

- Matriz original:
[[ 1. -4.]
 [12.  3.]
 [ 7.  5.]]
- Le asignamos el valor 4 a los elementos de la columna 0:
[[ 4. -4.]
 [ 4.  3.]
 [ 4.  5.]]
- Dividimos por 3 la columna 1:
[[ 4.         -1.33333333]
 [ 4.          1.        ]
 [ 4.          1.66666667]]
- Multiplicamos por 5 la fila 1:
[[ 4.         -1.33333333]
 [20.          5.        ]
 [ 4.          1.66666667]]
- Le sumamos 1 a toda la matriz:
[[ 5.         -0.33333333]
 [21.          6.        ]
 [ 5.          2.66666667]]


In [ ]:
#Ejercicios

lista_de_listas=[ [-44,12], 
                  [12.0,51], 
                  [1300, -5.0]]
a = np.array(lista_de_listas)

print("Matriz original")
print(a)


# Restarle 5 a la fila 2 de la matriz
#IMPLEMENTAR
print(a)

# Multiplicar por 2 toda la matriz
#IMPLEMENTAR
print(a)

# Dividir por -5 las dos primeras filas de la matriz
#IMPLEMENTAR
print(a)


#Imprimir la ultima fila de la matriz
ultima_fila=0 # IMPLEMENTAR
print(ultima_fila)

Matriz original
[[ -44.   12.]
 [  12.   51.]
 [1300.   -5.]]
[[ -44.   12.]
 [  12.   51.]
 [1300.   -5.]]
[[ -44.   12.]
 [  12.   51.]
 [1300.   -5.]]
[[ -44.   12.]
 [  12.   51.]
 [1300.   -5.]]
0
